
import { ShopType, UnitType, Product, AppSettings } from './types';

export const CATEGORIES = {
  [ShopType.STATIONERY]: [
    'Pen', 'Pencil', 'Copy', 'Marker', 'Highlighter', 'Register',
    'File', 'Folder', 'Eraser', 'Ruler', 'Geometry Box', 'Ink',
    'Paper', 'Envelope', 'Calculator', 'Art Supplies', 'Other'
  ],
  [ShopType.GENERAL_STORE]: [
    'Grains', 'Flour', 'Sugar', 'Salt', 'Lentils', 'Dairy', 'Eggs',
    'Snacks', 'Biscuits', 'Beverages', 'Juices', 'Spices', 'Masala',
    'Soap', 'Shampoo', 'Detergent', 'Oil', 'Ghee', 'Toiletries',
    'Frozen', 'Canned', 'Bread', 'Tea', 'Coffee', 'Other'
  ],
};

export const DEFAULT_SETTINGS: AppSettings = {
  businessName: 'BizLedger',
  businessAddress: 'Your Store Address',
  businessPhone: '',
  currencySymbol: 'Rs.',
  taxRate: 0,
  taxEnabled: false,
  defaultLowStockThreshold: 5,
  theme: 'light',
  pinLock: null,
  invoiceCounter: 1001,
  autoBackupInterval: 50,
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 's1',
    shopType: ShopType.STATIONERY,
    name: 'Blue Gel Pen',
    category: 'Pen',
    sku: 'PEN001',
    purchasePrice: 5,
    sellingPrice: 10,
    unitType: UnitType.UNIT,
    stock: 100,
    lowStockThreshold: 20,
    createdAt: Date.now(),
  },
  {
    id: 's2',
    shopType: ShopType.STATIONERY,
    name: 'A4 Register 200pg',
    category: 'Register',
    sku: 'REG001',
    purchasePrice: 40,
    sellingPrice: 75,
    unitType: UnitType.UNIT,
    stock: 50,
    lowStockThreshold: 10,
    createdAt: Date.now(),
  },
  {
    id: 's3',
    shopType: ShopType.STATIONERY,
    name: 'HB Pencil Box (12pcs)',
    category: 'Pencil',
    sku: 'PNC001',
    purchasePrice: 30,
    sellingPrice: 50,
    unitType: UnitType.UNIT,
    stock: 40,
    lowStockThreshold: 10,
    createdAt: Date.now(),
  },
  {
    id: 's4',
    shopType: ShopType.STATIONERY,
    name: 'Whiteboard Marker (Blue)',
    category: 'Marker',
    sku: 'MRK001',
    purchasePrice: 20,
    sellingPrice: 35,
    unitType: UnitType.UNIT,
    stock: 60,
    lowStockThreshold: 15,
    createdAt: Date.now(),
  },
  {
    id: 'g1',
    shopType: ShopType.GENERAL_STORE,
    name: 'Basmati Rice',
    category: 'Grains',
    sku: 'RIC001',
    purchasePrice: 80,
    sellingPrice: 120,
    unitType: UnitType.KG,
    stock: 50,
    lowStockThreshold: 5,
    createdAt: Date.now(),
  },
  {
    id: 'g2',
    shopType: ShopType.GENERAL_STORE,
    name: 'Milk Chocolate Bar',
    category: 'Snacks',
    sku: 'SNK001',
    purchasePrice: 15,
    sellingPrice: 20,
    unitType: UnitType.UNIT,
    stock: 30,
    lowStockThreshold: 5,
    createdAt: Date.now(),
  },
  {
    id: 'g3',
    shopType: ShopType.GENERAL_STORE,
    name: 'Sunflower Oil 1L',
    category: 'Oil',
    sku: 'OIL001',
    purchasePrice: 280,
    sellingPrice: 320,
    unitType: UnitType.UNIT,
    stock: 24,
    lowStockThreshold: 5,
    createdAt: Date.now(),
  },
  {
    id: 'g4',
    shopType: ShopType.GENERAL_STORE,
    name: 'Wheat Flour',
    category: 'Flour',
    sku: 'FLR001',
    purchasePrice: 55,
    sellingPrice: 70,
    unitType: UnitType.KG,
    stock: 80,
    lowStockThreshold: 10,
    createdAt: Date.now(),
  }
];
